[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86.json"

[target.'cfg(all(target_os = "none", target_arch = "x86"))']
runner = ["qemu-system-i386", "-kernel"]
